#!/bin/bash

ROOT="../tmp-output"

# mirror directory structure
find . -type d | cpio -dumpl "$ROOT"

for source_file in $(find . -type f -name "*.md" ); do
    echo "Generating html for ${source_file} -> ${source_file%.*}.html"
    pandoc -s -S --toc -c "/style.css" -o "$ROOT/${source_file%.*}.html" "${source_file}"
done

# generate site index
#echo "Generating index"
#
#OUTPUT="site-index.md"
#
#i=0
#echo "# Site Index" > $OUTPUT
#for filepath in `find "$ROOT" -mindepth 1 -type d | sort`; do
#  path=`basename "$filepath"`
#  echo "- $path" >> $OUTPUT
#  for i in `find "$filepath" -mindepth 1 -type f -name "*.html" | sort`; do
#    file=`basename "$i"`
#    echo "Found	-"\[$file\]"($path/$file)"
#    echo "    - "\[$file\]"($path/$file)" >> $OUTPUT
#  done
#done
#
#pandoc -s -S -c style.css -o "../site-index.html" "$OUTPUT"
cp -R $ROOT/* ../.
#
#cat $OUTPUT
#
#rm "$OUTPUT"
