#!/bin/bash

ROOT="../output"

# mirror directory structure
find . -type d | cpio -dumpl "$ROOT"

for source_file in $(find . -type f -name "*.md" ); do
    echo "Generating html for ${source_file} -> ${source_file%.*}.html"
    pandoc -t html5 --self-contained --smart --toc -c "../style.css" -o "$ROOT/${source_file%.*}.html" "${source_file}"
done

# generate site index
echo "Generating index"

OUTPUT="site-index.md"

i=0
echo "# Site Index" > $OUTPUT
for filepath in `find "$ROOT" -mindepth 1 -type d | sort`; do
    path=`basename "$filepath"`
    echo "- $path" >> $OUTPUT
    for i in `find "$filepath" -mindepth 1 -type f -name "*.html" | sort`; do
        file=`basename "$i"`
        echo "Found	-"\[$file\]"($path/$file)"
        echo "    - "\[$file\]"($path/$file)" >> $OUTPUT
  done
done

pandoc -t html5 --self-contained --smart -c ../style.css -o "$ROOT/site-index.html" "$OUTPUT"

cp -r ../static/ ../output/.

#
cat $OUTPUT
#
rm "$OUTPUT"
